package ai

import (
	"context"
	"fmt"

	"github.com/geekabo93/lingofetch/internal/pkg/resources"
	"google.golang.org/genai"
)

// GeminiService handles AI-powered definition generation using the official Gemini SDK
type GeminiService struct {
	client *genai.Client
	models []string
}

// Ensure GeminiService implements Provider interface
var _ Provider = (*GeminiService)(nil)

// NewGeminiService creates a new Gemini AI service using the official SDK
func NewGeminiService(ctx context.Context, apiKey string, models []string) (*GeminiService, error) {
	if apiKey == "" {
		return nil, fmt.Errorf("Gemini API key is required")
	}

	client, err := genai.NewClient(ctx, &genai.ClientConfig{
		APIKey:  apiKey,
		Backend: genai.BackendGeminiAPI,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create Gemini client: %w", err)
	}

	if len(models) == 0 {
		models = []string{"gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-flash", "gemini-1.5-pro"}
	}

	return &GeminiService{
		client: client,
		models: models,
	}, nil
}

// GenerateDefinition generates a comprehensive definition for a word using Gemini in the target language
func (s *GeminiService) GenerateDefinition(ctx context.Context, word, targetLanguage, contextStr, pageLanguage, sourceLanguage string) (*WordAnalysis, error) {
	prompt, err := resources.GetPrompt("definition", map[string]string{
		"Word":           word,
		"TargetLanguage": targetLanguage,
		"Context":        contextStr,
		"PageLanguage":   pageLanguage,
		"SourceLanguage": sourceLanguage,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get prompt: %w", err)
	}

	// Sequence of models to try
	modelsToTry := s.models

	var lastErr error
	var resp *genai.GenerateContentResponse

	for _, modelName := range modelsToTry {
		fmt.Printf("[AI] Attempting Gemini analysis with model: %s...\n", modelName)
		resp, err = s.client.Models.GenerateContent(ctx, modelName, genai.Text(prompt), nil)
		if err == nil {
			fmt.Printf("[AI] SUCCESS: Analysis complete using %s\n", modelName)
			break
		}
		lastErr = err
		fmt.Printf("[AI] Gemini %s failed: %v\n", modelName, err)
	}

	if resp == nil {
		return nil, fmt.Errorf("all Gemini models failed. Last error: %w", lastErr)
	}

	if len(resp.Candidates) == 0 || len(resp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("no content generated by Gemini")
	}

	// The official SDK returns parts, we take the first text part
	var text string
	for _, part := range resp.Candidates[0].Content.Parts {
		if part.Text != "" {
			text = part.Text
			break
		}
	}

	if text == "" {
		return nil, fmt.Errorf("empty response from Gemini")
	}

	fmt.Printf("[Debug] [Gemini SDK] Raw Response: %s\n", text)
	return parseDefinition(text, word)
}

// Name returns the provider name
func (s *GeminiService) Name() string {
	return "gemini"
}

// Close closes the client (SDK might not require explicit close if it's stateless, but we follow the interface)
func (s *GeminiService) Close() error {
	return nil
}
